---
image: mischief/docker-golang

env:
  - GOROOT=/usr/local/go
  - GOPATH=/var/cache/drone
  - PATH=$GOPATH/bin:$PATH

script:
  - env
  - ./shipit.sh

deploy:
  git:
    target: git@github.com:vito/drone-pipeline-spike.git
    force: true
    branches:
      master: passed-integration
      passed-integration: passed-deploy
