---
image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - GOPATH=/var/cache/drone
  - PATH=$GOPATH/bin:$PATH
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}

script:
  - env
  - ./shipit.sh

cache:
  - .blobs
  - .final_builds

deploy:
  git:
    target: git@github.com:vito/drone-pipeline-spike.git
    force: true
    branches:
      master: passed-integration
      passed-integration: passed-deploy
