---
image: cloudfoundry/diego-pipeline

env:
  - GOROOT=/usr/local/go
  - GOPATH=/var/cache/drone
  - PATH=$GOPATH/bin:$PATH
  - BOSH_USER={{BOSH_USER}}
  - BOSH_PASSWORD={{BOSH_PASSWORD}}

script:
  - env
  - ln -s /tmp/release-blobs .blobs
  - ln -s /tmp/release-final-builds .final_builds
  - ./shipit.sh

cache:
  - /tmp/release-blobs
  - /tmp/release-final-builds
